### ISSUE TITLE
dinput8 make game Not working

### ISSUE THREAD

**Issue by zhdy-z** [samuelgr/Xidi#1]
Replace system dinput8.dll with xidi dinput8.dll, may game can't work. dose xidi dinput8.dll need " system dinput8.dll" to work?

**Comment by samuelgr** [comment]
Do not replace the system dinput8.dll with Xidi dinput8.dll. Xidi needs the system dinput8.dll to function correctly.

Put Xidi dinput8.dll into the same directory as the game exe file.
