### ISSUE TITLE
XInputNative axes don't near-match default Win10 behavior (sans triggers)

### ISSUE THREAD

**Issue by BinToss** [samuelgr/Xidi#10]
Solution: Dedicate Axis 5 to Left Trigger and Axis 6 to Right Trigger.

With an Xbox One controller, the controls in the following screenshot would normally be...
- Axis 1-
- Axis 1+
- Axis 2-
- Axis 2+
- Axis 3-
- Axis 3+
- Axis 4-
- Axis 4+

With Axis 5 being shared by the triggers.
![haloce 2021-03-07 21-49-35](https://user-images.githubusercontent.com/7243190/110280389-91e9c680-7f8f-11eb-934c-7237040828b7.png)

Here's two examples of how Xbox 360/One controllers normally map
https://github.com/SnowyMouse/chimera/blob/master/controller_config/windows/xbox_360.txt
https://github.com/SnowyMouse/chimera/blob/master/controller_config/windows/xbox_one.txt

**Comment by BinToss** [comment]
It's also possible that the classic PC ports of Halo:CE were made with a very different understanding of DirectInput seeing as the Axes are unnamed and buttons start at 0 instead of 1.

**Comment by samuelgr** [comment]
See the documentation: https://github.com/samuelgr/Xidi#mapping-controller-buttons-and-axes

You will want to use `XInputSharedTriggers`, not `XInputNative`.

**Comment by samuelgr** [comment]
I am not sure how this particular game (shown in the screenshot) is interpreting axis numbers, but my guess it gets them as the . Internally Xidi just numbers them in the order X, Y, Z, RotX, RotY, and RotZ.

Is there a particular reason why the specific axis number matters? As far as Xidi is concerned, making this change is just a matter of swapping the order of a few constant values.

**Comment by samuelgr** [comment]
Closing because the axes have been numbered this way for several years now and I haven't heard of any applications breaking because the internal axis numbering is different.

**Comment by BinToss** [comment]
This was a request for changes that would reduce a 10+ line change in a config file to a two-line change.

I realize now that I didn't give enough context.

The Gearbox PC port of Halo doesn't have the graphical input prompts found in the Xbox releases and later rereleases. That old port maps KB+M inputs to readable, plain text names e.g. Middle Mouse Button. Gamepads, however, lack that. Where one would expect something like "Press |LT| to throw grenade" with a graphical trigger, it instead prints "Press Axis #5 - to throw grenade.", depending on the gamepad and its software configuration.

Chimera–a QoL code-injection mod–can read config files to map those gamepad input strings to readable ones. Still plain text, but "Press Left Trigger to throw grenade" is better than "what does this axis map to?".

When using Xidi to work around Windows' flight-sim-optimized axis mappings, Chimera obviously needs new configs for each type of controller connected via Xidi. And that's where the extremely minor aggravation comes in.

I don't recall why I was so hard-set on this being changed in Xidi.
