### ISSUE TITLE
Text-File Custom Mapping - Mouse emulation

### ISSUE THREAD

**Issue by BinToss** [samuelgr/Xidi#15]

**Comment by v00d00m4n** [comment]
Hows progress with mouse emulation so far?

**Comment by samuelgr** [comment]
I have some ideas but nothing to share at this time.

**Comment by v00d00m4n** [comment]
So still no mouse emulation?

**Comment by samuelgr** [comment]
No, nothing yet. It is not the highest priority for me at the moment, though I do agree it is a good idea.

**Comment by samuelgr** [comment]
Implemented and released in v4.1.0.
