### ISSUE TITLE
Mapping D-Pad / POV Hat as Buttons 13-16

### ISSUE THREAD

**Issue by Rufoo** [samuelgr/Xidi#16]
Hi mate,

I'll get the usual fluffery out of the way first. Xidi has been amazing and have used it on numerous things like Splinter Cell: Conviction and Dead or Alive 5: Last Round. It's been an absolute godsend! Thank you for your efforts. :)

Now onto the slimy part where I ask something from ya after buttering you up some. Can you add a mapper which treats the D-Pad / POV hat of the Xinput controller as buttons 13-16 instead of an axes or POV?

I've been re-enabling gamepad support in the original SC and SC:PT for PC - which never had them but Xidi makes it possible to restore it. However, there is no way to bind the D-Pad / POV hat. Using Xinput Plus, if I use the DirectInput Output function and advise it to bind the D-Pad / POV as button 13-16, I can make the game do what I need. But Xinput Plus isn't nearly as elegant solution as Xidi and was only employed to "test" my theory about POV as buttons 13-16.

Thanks for your time. :)

PS: You got a donation area? Happy to shoot you a beer for your efforts and as thanks for enabling my fave fighting game, DOA5:LR to live on! :D

**Comment by Rufoo** [comment]
I forked the binary and created my own mapper. So I'm closing the issue.

Still, I'm happy to get you that beer. Shoot the details over. :)

**Comment by samuelgr** [comment]
I am not much of a beer drinker but thank you for the offer 🙂

Glad to hear that it was easy enough to modify the code to get this working. The longer-term solution to avoid needing to change the code at all is supporting custom mappings in text file configurations (#4).
