### ISSUE TITLE
Legacy Of Kain: Defiance - Can't Map Controls to Dpad

### ISSUE THREAD

**Issue by Spart4n** [samuelgr/Xidi#17]
I'm pretty sure that the Dpad mapped to swapping soul reaver types and swapping between planes, but I can't seem to get the Dpad to map to anything in game.

**Comment by samuelgr** [comment]
Is it a known fact that the dpad used to work this way? I was under the impression that this game worked perfectly after fixing #7.

The dpad is presented to the game the same way with and without Xidi and consistently with how older controllers presented dpads. I've never had it do anything when I tried playing this game either.

To get the dpad working one option is to create a new mapper that treats the dpad as buttons. This will be easier to do once Xidi supports reading mappers from configuration files.

**Comment by Spart4n** [comment]
I was going off of the controller configurations that were available for
the console versions, I thought they'd be the same.

**Comment by samuelgr** [comment]
If there is some confirmation that this game worked with the dpad using an older DirectInput controller but that the dpad doesn't work with Xidi then please re-open and I can try to take a look.
