### ISSUE TITLE
Rumble support?

### ISSUE THREAD

**Issue by ViperAcidZX** [samuelgr/Xidi#19]
Is there a way to get controller vibration feedback working with Xidi? I have been using Xidi + Hookshot on an Xbox One controller via the included USB cable so far with the obscure 2004 PC port of Mega Man X8 (not to be mistaken for the version of Mega Man X8 included in Mega Man X Legacy Collection 2) and this PC port does support vibration feedback but the Xidi configuration I'm using is not allowing the game to toggle the vibration setting and it's grayed out instead. Oddly enough, without Xidi the option to toggle controller vibration is available but not with Xidi and Hookshot are hooking into the game's controller inputs.

With Xidi:
![_HookshotLauncher_MEGAMANX8-2021_12_08_14-49-34](https://user-images.githubusercontent.com/19318128/145274760-74a64e9e-7fde-456b-931a-80332e0f7891.png)

Without Xidi:
![_HookshotLauncher_MEGAMANX8-2021_12_08_14-50-51](https://user-images.githubusercontent.com/19318128/145274781-de39ba71-544f-4d29-8900-5c27f66049a4.png)

**EDIT:** Never mind, I failed to see the lack of vibration support at the moment on the last second of the readme. I'll close but I hope rumble support gets implemented.

**Comment by samuelgr** [comment]
Force feedback support will be part of the next release. I've actually been testing it with the free trial version of this game, among others.

**Comment by samuelgr** [comment]
Force feedback is part of v4.0.0.
