### ISSUE TITLE
Error message with winmm.dll x64

### ISSUE THREAD

**Issue by ooGEoo** [samuelgr/Xidi#2]
Hello,
I'm trying to get winmm.dll working with Snes9x-x64 at Windows 10, but i get the following message:
Der Prozedureinsprungspunkt "mciSendStringW" wurde in der DLL "C:\\Windows\System32\MSVFW32.dll" nicht gefunden.
Translation:
The procedure entry point "mciSendStringW" was not found in the DLL "C:\\Windows\System32\MSVFW32.dll".

Update:
I've tried VisualBoyAdvance with the Win32 winmm.dll and there I get the same message, but with "mciSendStringA".

Thank you!

**Comment by samuelgr** [comment]
Thanks for pointing this out. I'll need to add the mci family of functions to winmm's exports.
