### ISSUE TITLE
Vibration is unavailable in Legacy of Kain: Defiance

### ISSUE THREAD

**Issue by samuelgr** [samuelgr/Xidi#23]
Even with Xidi v4.0.0 the vibration menu option is grayed out in Legacy of Kain: Defiance. In order to investigate this further I will need some assistance. The Xidi log shows that the game successfully invokes many parts of the DirectInput API for vibration, even to the point of creating a force feedback effect option, and then suddenly gives up for no apparent reason.

I tried this game on Windows 7 and XP using a real Logitech RumblePad 2 with the official Logitech drivers installed. The force feedback driver is installed and works properly via DirectInput, yet for some reason with this game the vibration option is still grayed out.

What I need is some additional information on a **working combination** of controller hardware and Windows version in order to investigate further. Either that or some additional technical insight into what this game needs internally to allow vibration to be available.

**Comment by UncleStark** [comment]
maybe xinputplus make some help? https://community.pcgamingwiki.com/files/file/2265-xinput-plus-v415290/
but I couldn't inject his dll into the game even using hookshot and xinputplus loader

**Comment by r2rX** [comment]
> What I need is some additional information on a **working combination** of controller hardware and Windows version in order to investigate further. Either that or some additional technical insight into what this game needs internally to allow vibration to be available.

@samuelgr Out of curiosity, have you tried using your Rumblepad, and its drivers, in Windows 10/11? (Hope you've been well, otherwise).

**Comment by samuelgr** [comment]
> @samuelgr Out of curiosity, have you tried using your Rumblepad, and its drivers, in Windows 10/11? (Hope you've been well, otherwise).

Yes, I tried that first before trying with Windows 7 and XP.

**Comment by r2rX** [comment]
I've sourced a Logitech F510 pad to try and help out. Once I've received it, I'll test it and report back here.

**Comment by Manu270891** [comment]
Vibration isn't working on Metal Gear Solid 2: Substance either.

**Comment by samuelgr** [comment]
Some new feedback from @r2rX in #6 indicates that vibration actually works in Defiance despite the menu option being grayed out. Maybe the UI is a bug in the game but it does not seem like this is an issue anymore.

**Comment by samuelgr** [comment]
I also tested this game myself using the GOG version on Windows 11. While the menu option is grayed out, vibration indeed does work during normal gameplay with Xidi v4.0.2.

**Comment by r2rX** [comment]
Thank you very much, @samuelgr for all your time and effort on this project. As bonus feedback, Xidi 4.0.2 also works great with Blood Omen 2.
