### ISSUE TITLE
Wrong language selection at the beginning of Rayman 2

### ISSUE THREAD

**Issue by costantino2000** [samuelgr/Xidi#27]
With Xidi installed, every time I launch the game the language selected in the list of languages is always the one before the last selection. This doesn't happen without Xidi. It's like the cursor is getting positioned in the entry before the one where it's supposed to actually be. Here is a screenshot, the red one is the previously selected one, usually it will just show in yellow the menu item the cursor is in, and pressing the confirm button will select spanish instead of italian (this means you have to move the cursor down every time you start the game):

![immagine](https://user-images.githubusercontent.com/86307814/177220497-187a4c56-da96-478a-9b34-7eaafd0725a8.png)

I have a custom config file I got from https://github.com/icup321/Ray2Fix:

[Xidi.txt](https://github.com/samuelgr/Xidi/files/9106119/Xidi.txt)

**Comment by samuelgr** [comment]
Thanks for reporting this. I would not be at all surprised if many more games were affected. There was an initial controller state bug that I fixed in aac8a6a13e586ab25aef2194b50445c6d7e523d9, which I just released as v4.0.1. Please give it a try.
