### ISSUE TITLE
Opening Rayman 2 with only the keyboard connected gives the "up key held" input to the game

### ISSUE THREAD

**Issue by costantino2000** [samuelgr/Xidi#28]
If you open Rayman 2 with only the keyboard connected there is a peculiar behaviour with the input. The main menu works fine, but going to New Game will make the first letter of the save naming menu start spinning, preventing you from creating the save, and loading a saved game will make the game act like you are always pressing the up key. This makes the game unplayable (because you are forced to play like you are always holding the up key) and forces you to remove xidi if you can't have the controller connected. This is the configuration file I'm using, it's from https://github.com/icup321/Ray2Fix:

[Xidi.txt](https://github.com/samuelgr/Xidi/files/9106032/Xidi.txt)

Here a screenshot of the menu for context, the first letter is spinning:

![screen](https://user-images.githubusercontent.com/86307814/178833420-210afa3e-980c-4f39-a925-97b28c5b1403.png)

**Comment by samuelgr** [comment]
It might not look like it, but beneath the hood this is the same problem as #27. I'll post updates over there. Suffice it to say both issues are fixed in aac8a6a13e586ab25aef2194b50445c6d7e523d9.
