### ISSUE TITLE
Issues with x86 winmm.dll with Windows 7

### ISSUE THREAD

**Issue by 0100101000101** [samuelgr/Xidi#3]
Hi, thanks for this interesting project.
I have Windows 7 x64 and I want to use Xidi with Xebra, a Playstation emulator.
This emulator uses winmm for joypads; however when I start Xebra with your dll it tells me that the XINPUT1_4.dll file is missing and the emulator does not take the commands.
I have read that that file is contained in the Windows 8 SDK libraries.
Can anything be done for Windows 7?
Thank you in advance.

**Comment by samuelgr** [comment]
As a workaround, you can try copying xinput1_3.dll into the same directory as Xebra and Xidi, then rename it to xinput1_4.dll.

Please note, though, that Xidi is not built for Windows 7, so even if this workaround appears initially to work it is not guaranteed to work fully and could break with future versions of Xebra and/or Xidi. I have also not tested this workaround.
