### ISSUE TITLE
Default ini with comments should be included with release packages.

### ISSUE THREAD

**Issue by v00d00m4n** [samuelgr/Xidi#32]
It a little painfull to manually shape ini after downloading Xidi. Please consider to do a quick upate with base ini with all available options, mostly commented out

**Comment by samuelgr** [comment]
There is already a pretty complete example in the README.md file which is displayed on Github and packaged with releases. Have a look at the "Configuring Xidi" section and you should see it. It contains all the defaults, except for custom mappers which don't really have a default (those are documented and examples provided further down).
