### ISSUE TITLE
Enhancement - ini option - Use only specified player number's controller

### ISSUE THREAD

**Issue by bangstk** [samuelgr/Xidi#36]
This is mostly useful for XInput -> Directinput remapping, and is a feature XInputPlus has.

An ini setting to configure the instance to ignore all XInput controllers except for a specified player number.

This is useful for instance for emulating splitscreen by launching multiple instances of a game that does not handle multiple joystick devices/gamepads properly, and therefore should get each instance filtered to a specified XInput player number. So that the player 1 instance ini can be set to only take input from the Player 1 gamepad, and the player 2 instance ini can be set to only take input from the Player 2 gamepad, and so on.

Thanks!

**Comment by samuelgr** [comment]
Implemented in e87a58a277d696198af416fcbe5f4577e9232b70, replacing the INI option MaxVirtualControllerCount with ActiveVirtualControllerMask.

Following your example, you could give one of these to each instance.

```ini
[Workarounds]
; Only player 1
ActiveVirtualControllerMask = 0x01
```

```ini
[Workarounds]
; Only player 2
ActiveVirtualControllerMask = 0x02
```

```ini
[Workarounds]
; Only player 3
ActiveVirtualControllerMask = 0x04
```

```ini
[Workarounds]
; Only player 4
ActiveVirtualControllerMask = 0x08
```
