### ISSUE TITLE
Steam virtual xinput triggers not recognized

### ISSUE THREAD

**Issue by bangstk** [samuelgr/Xidi#37]
This concerns launching a game from Steam using Steam's controller config, regardless of the actual controller used. Steam's controller config results in a Steam virtual xinput controller being presented to the game. There is an issue when this game is using Xidi (for instance to make a virtual Directinput controller)

Naturally this is a grotesque stacking of various xinput wrappers already whose support is already dubious and I understand not wanting to look into it.

However, it almost already works except for one thing: input from Steam's virtual LT/RT triggers (analog, nor digital) is not recognized by Xidi.
All other controls work.

Possibly Steam's xinput wrapper presents its virtualized xinput triggers/axes in a slightly different way than expected or standard (which however works with xinput games natively)

To reproduce: Enable Steam controller remapping via Steam->settings->controller->general settings
Add a Non-Steam game that uses Xidi
Set up a Steam controller profile that outputs LT or RT from any gamepad button
Result: Xidi seems not to see anything configured to output LT/RT, but will handle input from any other xinput controls specified in the steam controller profile.

Fixing this would improve support for say, Steam Controller, Steam Deck, or any game launched via Steam.

**Comment by samuelgr** [comment]
I tried this with Sonic Heroes, which uses Xidi's dinput8 form, and cannot reproduce the problem. This is using the Steam client built on November 16, 2022.

With an Xbox controller set to enable trigger output via the default axes 2 and 5, I set up the game's controller configuration to map LS and RS to left and right triggers, as shown. Normally the game ignores LS and RS, but with this controller layout definition LS and RS do the same thing as LT and RT.


![Controller Settings](https://user-images.githubusercontent.com/6945267/202871694-f8f6e6c9-f9b3-4d5c-b82f-7b90dbaf420e.png)

![Game Settings](https://user-images.githubusercontent.com/6945267/202871700-1f6bf6e6-3c0a-4826-bc12-64e7bb69e19e.png)
