### ISSUE TITLE
Xidi not working on "tomb3decomp", "tomb4decomp" and "tomb5decomp"

### ISSUE THREAD

**Issue by Manu270891** [samuelgr/Xidi#41]
Hi, 

Xidi isn't working on "tomb3decomp" (https://github.com/Trxyebeep/tomb3), "tomb4decomp" (https://github.com/Trxyebeep/TOMB4) and "tomb5decomp" (https://github.com/Trxyebeep/TOMB5), while "XInput Plus" is working. I've tried both "dinput.dll" and "dinput8.dll" and none of them seem to be working.

Thanks.

**Comment by samuelgr** [comment]
Could you please post some debug logs?

Xidi.ini:

```ini
[Log]
Enabled = yes
Level = 4
```

**Comment by Manu270891** [comment]
Here are the three log files. I just noticed that tomb5decomp used dinput, not dinput8 and does indeed work, but the game doesn't seem to detect dead zones and the left analog stick is just too sensitive, but this is not a Xidi issue. tomb3decomp and tomb4decomp seem to be using dinput8 and, while the log says Xidi is attaching to the game, I just can't set the controls properly (analog triggers are not detected, for example).

[Xidi_DInput_PCTomb5.exe_10492.log](https://github.com/samuelgr/Xidi/files/10050542/Xidi_DInput_PCTomb5.exe_10492.log)
[Xidi_DInput8_tomb3.exe_11048.log](https://github.com/samuelgr/Xidi/files/10050543/Xidi_DInput8_tomb3.exe_11048.log)
[Xidi_DInput8_tomb4.exe_12492.log](https://github.com/samuelgr/Xidi/files/10050544/Xidi_DInput8_tomb4.exe_12492.log)

**Comment by samuelgr** [comment]
From the logs, tomb3 and tomb4 do load Xidi but appear to use DirectInput only for the keyboard. Could you please try the winmm form of Xidi and see if that helps?

**Comment by Manu270891** [comment]
Using winmm simply doesn't generate any log. Here is another log for "tomb4decomp" now selecting the "joystick" option in the control settings. Maybe now the log show actual gamepad usage.
[Xidi_DInput8_tomb4.exe_19140.log](https://github.com/samuelgr/Xidi/files/10065605/Xidi_DInput8_tomb4.exe_19140.log)

**Comment by samuelgr** [comment]
From the [tomb3](https://github.com/Trxyebeep/tomb3/blob/c4cbc6c7ea57248c95397f88469448ac73cb14b9/tomb3/specific/di.cpp#L36) and [tomb4](https://github.com/Trxyebeep/TOMB4/blob/d7cefec17a3988051981b83c267fc7cff0ce0ce8/TOMB4/specific/input.cpp#L622) code, they are using WinMM APIs for game controller communication.

If the WinMM form of Xidi isn't loading then you can try using the HookModule + WinMM method of loading Xidi and, failing that, post a HookModule Xidi log here and/or ask the project owners for help. But this isn't itself a problem with Xidi.

The deadzone issue is already tracked in #30.
