### ISSUE TITLE
Jazz Jackrabbit 2 not working (winmm.dll)

### ISSUE THREAD

**Issue by Hexaae** [samuelgr/Xidi#43]
Can't make Jazz Jackrabbit 2 load the winmm.dll (32bit 4.1.0.0) from Xidi (I have no log output either) using this xidi.ini:
```
[Mapper]
Type = DigitalGamepad

[Log]
Enabled = yes
Level = 4
```
 Tried also the GOG collection and doesn't work as well: arcade joystick directions are ignored (Hori Fighting Stick MINI, DPAD XInput for directions), only buttons do work.
(See also https://github.com/samuelgr/Xidi/issues/5 )

**Comment by Hexaae** [comment]
Tried also cfg https://github.com/samuelgr/XidiGameConfigurations/tree/master/GameConfigurations/Jazz%20Jackrabbit%202 but still didn't work.

**Comment by samuelgr** [comment]
This is not a Xidi issue. I have verified for myself that Jazz Jackrabbit 2 works correctly with the WinMM form of Xidi v4.1.0. Double-check that you are indeed using the 32-bit version of the DLL and, if that still fails, you can try using the HookModule form of Xidi to help (though from my own experience it is not necessary for this game).

**Comment by Hexaae** [comment]
What version of JJR do you have? Because with retail CD or GOG version it doesn't work.

**Comment by samuelgr** [comment]
I just re-tried with a freshly-installed and unmodified Jazz Jackrabbit 2 from GOG and it works perfectly just by dropping in the 32-bit winmm.dll file from Xidi v4.0.1.

See if the HookModule method can help you, but this is not a Xidi problem.

**Comment by Hexaae** [comment]
**SOLUTION**
I've finally found the reason why it didn't work... I had some compatibility fixes active on "Jazz2.exe", in particular ANY of these will cause Xidi's winmm.dll to fail:

From Windows Compatibility Administrator 32bit:
- HeapForceGrowable
- HeapValidateFrees
- DisableDXMaximizedWindowedMode (equal to compatibility option "[Disable fullscreen optimization](https://www.howto-connect.com/wp-content/uploads/How-to-Fix-Disabled-Disable-Fullscreen-Optimizations-in-Windows-10-image-3-e1526909270367.png)" )
- DisableThemes

You can try yourself enabling "Disable fullscreen optimization" compatibility option and see Xidi's winmm.dll not working anymore.

This is the first time I see this problem (I have plenty of fixed games with MS Application Compatibility Toolkit). JJR must be a very picky game.

**Comment by samuelgr** [comment]
Thank you for this very useful information. I was able to reproduce the problem by adding the "Disable fullscreen optimization" compatibility option to Jazz2.exe. Using the HookModule form of Xidi alongside the WinMM form solved it.

**Comment by Hexaae** [comment]
Interesting. Thank you for Xidi 👍
