### ISSUE TITLE
Colin McRae Rally 04 [dinput8.dll] - Xidi Virtual Controller is selected even if no USB controller is connected

### ISSUE THREAD

**Issue by francescoaracu** [samuelgr/Xidi#44]
On the Controller settings in-game, Xidi Virtual Controllers (from 1 to 4) are selectable (and remain selected) even if no controller is connected to my PC.

Xidi's `dinput8.dll` is on the latest version, Windows 11 version 22H2 is my OS. Another thing: I run this game through DxWnd.

**Comment by samuelgr** [comment]
This is intended behavior. It is part of the feature that allows [seamless controller changes](https://github.com/samuelgr/Xidi#what-to-expect-in-a-game) in the middle of a game.
