### ISSUE TITLE
Need for Speed III Hot Pursuit mapping problems

### ISSUE THREAD

**Issue by nex86** [samuelgr/Xidi#47]
Game detects input device, rumble also works, but I can't seem to map anything as its not correctly responding to any inputs. 
axis are completely maxed out, car fully accelerates and steers to the left without me doing anything.

the game works without issues on windows 10 computer, but I need it for steam deck.

**Comment by samuelgr** [comment]
If the game works perfectly with Xidi on Windows 10, but you are having trouble with Steam Deck, then it doesn't sound like a Xidi problem but rather a Steam Deck configuration problem.

I do not myself own a Steam Deck, but I know that other users (on here, on Reddit, etc.) have made Xidi work on the Steam Deck. Those would make for better venues getting help with Xidi on Steam Deck.
