### ISSUE TITLE
compatibility for windows 8.1 and 7

### ISSUE THREAD

**Issue by JaegerFox** [samuelgr/Xidi#52]
Most games that use Directinput are old and require few requirements, Windows 10 and 11 are already OS that demand more to the computer.
to take advantage of hardware that is still good enough to run these games.
I know there are alternatives like xinput plus, but xidi is much lighter and easier to configure and xidi is opensource.

and yes I installed Microsoft Visual C++ Redistributable and the error (0xc0000142) appears, I had this problem before with SH2 EE and a few weeks ago it was solved but only with dinput8, I need dinput.dll

**Comment by samuelgr** [comment]
Error 0xc0000142 is fixed in 0ad5223188d6dd9b28cfc77c6ed5ee047bfc2425 (see #49) and, as far as I know, has nothing to do with Windows 7 or 8.1. It will be part of the next release.
