### ISSUE TITLE
Chaos Legion PC - Bugs and crashes when accessing control configuration menu

### ISSUE THREAD

**Issue by ViperAcidZX** [samuelgr/Xidi#53]
I wanted to use Xidi with the PC port of Chaos Legion and, while it works, it also has some unfortunate bug menu and crashes when trying to change the controls between Gamepad and Keyboard configurations from the in-game menu. It was working at first, but when trying to change the controls, the game either breaks the _Gamepad 2_ configuration and prevent it from being selectable (which allows for right stick camera movement like in the PlayStation 2 version whereas _Gamepad 1_ maps it to the W key on keyboard) or the game hangs mid load of the configuration options and then just crashes to desktop. I have to use a workaround of removing Xidi, switch the input settings to _Gamepad 2_, put the Xidi files back, then avoid the control settings entirely unless I remove Xidi altogether. I used Xidi v4.1.1 with the Dinput8.dll file without needing to use Hookshot for this game with an Xbox Series controller connected via Bluetooth with Mayflash's MAGIC NS-2 adaptor. Below is my crashlog when I recreated the crash and errors with the game. I also wanted to submit a Xidi configuration with this game and a few other games, but unfortunately I cannot submit them into the configuration repository myself.

[Xidi_DInput8_ChaosLegion.exe_9668.log](https://github.com/samuelgr/Xidi/files/11192858/Xidi_DInput8_ChaosLegion.exe_9668.log)

**Comment by samuelgr** [comment]
There have been a lot of compatibility improvements since 4.1.1. Does a [recent development build](https://github.com/samuelgr/Xidi/files/11280017/Xidi-v4.1.2-dev.20.0%2B41885887.zip) help at all?

Does the crash also occur without Xidi?

**Comment by samuelgr** [comment]
I was able to obtain access to this game for the purpose of testing with it, and I can't point to a specific issue with Xidi to fix to make this game work better. The game appears to do a lot of very strange things, but I was not able to reproduce the issues reported here with Xidi.

From what I understand there are two issues here:

1. The game (sometimes) hangs and crashes to the desktop when entering the controller configuration menu.
    - Ironically, I was not able to reproduce this issue with Xidi, but I was able to reproduce it semi-regularly *without* Xidi.
    - What I found is that the game is *slow to enter* the controller configuration menu with Xidi and *less slow to enter* without Xidi. This is because the game enumerates DirectInput devices a very high number of times in very quick succession, and Xidi inserts its own processing each time that happens.
    - There seems to be an implementation issue with the game itself. In the logs and also in the debugger I see the game making incorrect out-of-order DirectInput API calls which, not surprisingly, fail. This only happens sometimes, though. If I add a bit more concurrency control to Xidi that makes the frequency drop even further, which suggests a threading issue.

2. "Gamepad 2" cannot be selected.
    - I was not able to reproduce this issue at all. Assuming the game made it into the controller configuration menu, I never had any trouble selecting Gamepad 2 and then actually using the right analog stick to control camera in the game.
    - I wonder if this is an issue with how the custom mapper is set up?

For Issue 2, could you please try removing your `Xidi.ini` and replacing it with this:

```ini
[Workarounds]
ActiveVirtualControllerMask = 0x01
```

**Comment by ViperAcidZX** [comment]
I tried the replacement Xidi config file and this did fix the inability to select Gamepad 2 settings in the Control options of the game. Sadly it stops me from using custom control bindings that I want to configure so that it can be applied to the game for an out-of-the-box set-up with the original PlayStation 2 controls when set to Gamepad 2 in the settings.

**Comment by samuelgr** [comment]
Thank you for the update. What this tells me is that the issue is not a Xidi bug but rather a problem with the custom mapper configuration you are trying to create.

If you would like assistance getting your custom mapper to work correctly, please feel free to open a Q&A topic and share the `Xidi.ini` configuration file you were trying to use. To open a Q&A topic, navigate to this repo's [Discussions](https://github.com/samuelgr/Xidi/discussions) tab, click "New discussion" and finally choose "Q&A" as the category.

We can also discuss how to submit game configurations to [XidiGameConfigurations](https://github.com/samuelgr/XidiGameConfigurations) if you wish.
