### ISSUE TITLE
[DOA5LR] Conflict with Xidi's dinput8.dll and Autolink 3.30's dinput8.dll

### ISSUE THREAD

**Issue by Yonalia** [samuelgr/Xidi#61]
Hello,

https://steamcommunity.com/app/311730/discussions/0/3115898713386779166/
As seen on the above Steam post, I am trying to use Xidi on the game Dead or Alive 5 Last Round as I play with an Xbox One Controller. 
After copying the Win32 files into the game directory, the tool works amazingly on its own as the Xbox One Controller works perfectly.

But I wish to use another tool called Autolink created by FallingCat, which adds many more features to the game:
https://steamcommunity.com/sharedfiles/filedetails/?id=1136603335
https://drive.google.com/file/d/1E1NPX-gWZeTwReYP4POzx2SjEmM5YsnO

Both tools use a dinput8.dll file that alters the game's controls upon launch.
Xidi fixes the problem of having no response on **_LT_** or **_RT_**, **_R3_** registering as start, and **_start_** registering as the intended behavior of RT. 
Autolink adds up keyboard commands only to the game.

I am clearly new to this, but could combining or merging both files to get one single dinput8.dll file work to get the best of both worlds?

**Comment by samuelgr** [comment]
I can't promise this will work, but one thing you can try is renaming the AutoLink dinput8.dll file to something else (let's say "autolink_mod.dll") and put it into the same directory as Xidi's dinput8.dll. Then add this to your `Xidi.ini` configuration file:

```ini
[Import]
dinput8.dll = autolink_mod.dll
```

**Comment by samuelgr** [comment]
If they have a solution available for renaming `dinput8.dll` to avoid the naming conflict, then you can try renaming Xidi's `dinput8.dll` to `dinput8ex.bin` as you described. Please go ahead and see if that helps.

**Comment by Yonalia** [comment]
We're almost there! Both dinput8.dll files seem to be working together after renaming Xidi's to dinput8ex.bin.
Only the keyboard commands added by Autolink do not function. 
The reason for this might because the game detects three more controllers when copying the four Win32 files into the game directory. Keyboard is not detected anymore.

( https://imgur.com/m6kYN32.jpg Screenshot of the game without the Xidi files. 

https://imgur.com/oNMhOlu.jpg After adding the four files from Win32 to the game directory).

Is there a way to configure Xidi so that keyboard gets detected?

**Comment by samuelgr** [comment]
You can try using this as your `Xidi.ini` to disable all but one of the virtual controllers:

```ini
[Workarounds]
ActiveVirtualControllerMask = 0x01
```

**Comment by Yonalia** [comment]
I am beyond excited to say that everything is working perfectly after adding this Xidi.ini configuration file to the game folder!
Thank you so much! I am really grateful to you for your help and for creating this amazing tool!

**Comment by samuelgr** [comment]
Great, I'm glad to hear everything works!
