### ISSUE TITLE
Solution for 8-way map on sticks and DPad

### ISSUE THREAD

**Issue by instinctualjealousy** [samuelgr/Xidi#66]
As of right now, the Split element allows a negative and a positive input for each axis, so 4-way is fully achievable with it. 4-way is inherently available on the per-direction DPad mapping.

Anyway, I've skimmed over the documentation, and I cannot figure a way to achieve maps-per-diagonal as well, and this makes sense. A diagonal simultaneously exists on both axes/buttons, and Xidi is configured per-axis/button.

Sonic Heroes could use this- it has a first-person freelook cam that is mapped to eight Numpad directions. I don't think this would be very feasible with the existing defined axes in a logical manner. New merged axis definitions would likely need to be added (StickLeftXY, StickRightXY), with an extended eight-value element ("8Way"?) valid only to it that defines each of the eight discrete directions. You couldn't use these alongside the original axis equivalents, and it'd probably have priority in-case someone had an errant Xidi.ini containing both.
```
StickLeftXY	= 8Way( [Up], [Down], [Left], [Right], [UpRight], [DownLeft], [DownRight], [UpLeft]  )
StickRightXY	= 4Way( [Up], [Down], [Left], [Right] )
```
This is just a brainstorm. It's a little messy like this- I'm having difficulty figuring out the most reasonable way to achieve this. Also above is my idea for a shorthand version of implementing 4-way versus the current way of achieving it.
```
DpadUp		= Keyboard(Numpad8)
DpadDown	= Keyboard(Numpad2)
DpadLeft	= Keyboard(Numpad4)
DpadRight	= Keyboard(Numpad6)
DpadUpRight	= Keyboard(Numpad9)
DpadDownLeft	= Keyboard(Numpad1)
DpadDownRight	= Keyboard(Numpad3)
DpadUpLeft	= Keyboard(Numpad7)
```
Since DPad is already split to four discrete directions, four more could simply be added- using the current 4-way behavior unless the 8-way values exist and are defined.

I apologize for the length.

**Comment by samuelgr** [comment]
Is there something in particular you are trying to achieve that the game doesn't already support?

```ini
DpadUp		= Keyboard(Numpad8)
DpadDown	= Keyboard(Numpad2)
DpadLeft	= Keyboard(Numpad4)
DpadRight	= Keyboard(Numpad6)
```

Just these four lines are enough to get the in-game camera working properly with diagonals; pressing two dpad directions at once makes the camera move diagonally.

Also, this game supports free camera motion via analog axes, which is mapped to the right analog stick in [this configuration file](https://github.com/samuelgr/XidiGameConfigurations/blob/master/GameConfigurations/Sonic%20Heroes/Xidi.ini).

**Comment by instinctualjealousy** [comment]
Okay, yeah, that makes sense. I'm so used to just dealing with games' problems with hardcoded axes that I just assumed Sonic Heroes doesn't support freecam control on stick due to dev oversight or something. I had assumed that the profile there just didn't take that into consideration since it's a pretty unimportant feature, and the devil's in the details when StandardGamepad alone fixes it.

I'd say this issue's pretty null now, so I'm going to close it. Almost all 8-way movement can be interpolated across 4 keys or buttons, and I can't imagine too many things would need this level of configuration, if anything at all. It's even likely that Sonic Heroes interpolates 2/4/6/8 to diagonals when holding adjacents- and even if it doesn't, it has native analog stick support as mentioned. Thank you for your clarification!
