### ISSUE TITLE
Force feedback multiplier or percent-adjustment

### ISSUE THREAD

**Issue by instinctualjealousy** [samuelgr/Xidi#67]
While the flexibility of defining and combining FF axes for each motor is a really nice feature, some games simply output way too much with no way of turning it down in game. A way to modify the saturation of feedback per-motor or per-element would be really nice to have.

A more advanced potential feature would be to control each axis' saturation on a MagnitudeProjection prior to summing them together. Sometimes one axes' effects might be more desirable at high intensity than another's, but the summing may still be desired.

**Comment by samuelgr** [comment]
A user-controlled "volume" for force feedback effects, along with some possible other controls, makes sense. I can't think of a good use case for exposing a setting for individual axes, though.

**Comment by instinctualjealousy** [comment]
Even a "volume" setting alone would be excellent.

**Comment by samuelgr** [comment]
Fully implemented in 18006b72666bfc0f0c4ff024ec80c2e78b76a795.
