### ISSUE TITLE
VibrationStrength not working with xboxone controllers

### ISSUE THREAD

**Issue by eadmaster** [samuelgr/Xidi#82]
i've tested the game with a wired [Xbox Wireless Controller](https://www.xbox.com/en-US/accessories/controllers/xbox-wireless-controller), and both the `VibrationStrength` and `ImpulseVibration*Multiplier` setting seems to have no effect.
(The controller is vibrating with same strength regardless of the setting)

**Comment by eadmaster** [comment]
Sorry, posted in the wrong repo...

**Comment by Goblan** [comment]
What repo did you want to post it on? I'm genuinely interested!

**Comment by eadmaster** [comment]
https://github.com/emoose/OutRun2006Tweaks/issues/51
