### ISSUE TITLE
Can't find the right syntax for this

### ISSUE THREAD

**Issue by Goblan** [samuelgr/Xidi#84]
Hi. I'm setting a custom mapper, but I'm stuck with this:

I want to map Right Stick Y axis positive to keyboard key PgUp, and Right Stich Y axis negative to keyboard key PgDn. This is what I've got so far:

> [Mapper]
> Type            		   = ModifiedExtendedGamepad
> Type.1                             = ModifiedExtendedGamepad
> Type.2                             = ModifiedExtendedGamepad
> Type.3                             = ModifiedExtendedGamepad
> Type.4                             = ModifiedExtendedGamepad
> 
> [CustomMapper:ModifiedExtendedGamepad]
> Template	    = ExtendedGamepad
> DpadUp              = Keyboard(UpArrow)
> DpadDown            = Keyboard(DownArrow)
> DpadLeft            = Keyboard(LeftArrow)
> DpadRight           = Keyboard(RightArrow)
> ButtonStart         = Keyboard(Enter)
> ButtonBack	    = Keyboard(TAB)

I want to add something like this:

StickRight(Y, +)	    = Keyboard(PgUp)
StickRight(Y, -)	            = Keyboard(PgDn)

But that obviously won't work, haven't been able to find the correct syntax for the axis part. Any help would be much appreciated.

**Comment by samuelgr** [comment]
Try using the Split element mapper, like this:

StickRightY = Split( Keyboard(PgUp), Keyboard(PgDown) )

**Comment by Goblan** [comment]
> Try using the Split element mapper, like this:
> 
> StickRightY = Split( Keyboard(PgUp), Keyboard(PgDown) )

Thanks so much. It worked nicely. I only had to switch the key order. For some reason Y+ was mapped to PgDn and Y- to PgUp. Writing it like this worked just as I expected:

StickRightY = Split(Keyboard(PgDn), Keyboard(PgUp))

Everything's pretty much perfect now. If only vibration strength could be toned down a little...

Thanks so much for Xidi and for your help.
