### ISSUE TITLE
Project Eden not working

### ISSUE THREAD

**Issue by Manu270891** [samuelgr/Xidi#86]
Hi,

I'm trying to use Xidi on ["Project Eden"](https://www.gog.com/en/game/project_eden).

The game uses WinMM. Apparently, "winmm.dll" can cause some troubles In Windows 11 (at least on my PC). Everytime I want to use Xidi in a game that uses "winmm.dll" i have to rename the file to "winm2.dll" and use [this script](https://github.com/YELLO-belly/ogg-winmm/tree/master/PS-Script) to modify the game exe, so that instead of looking for the "winmm.dll" file, the game looks for a "winm2.dll" file. This can also be archieved by using a hex editor on the game .exe file and replacing all the "winmm" strings for "winm2". I used the script in the .exe file for "Wallace & Gromit in Project Zoo" and it made Xidi work.

Unfortunately, Xidi does not seem to work on  Project Eden. The log files are being created, but there is not any change in-game, the controls can't be set correctly and editing the "Xidi.ini" file doesn't seem to make any difference.

Any clue why is this happening?

Thanks!

**Comment by samuelgr** [comment]
Could you please upload whatever Xidi log files you have? And are you sure that this game uses WinMM for game controllers? WinMM itself offers a lot of other functionality, so sometimes games will load it but then use something else for controller support. Have you tried the DInput and DInput8 forms, possibly with the HookModule as well?

**Comment by samuelgr** [comment]
This game requires HookModule + DInput to work with Xidi along with some workarounds. [This configuration file](https://github.com/samuelgr/XidiGameConfigurations/blob/master/GameConfigurations/Project%20Eden/Xidi.ini) should work as a good starting point.

**Comment by Manu270891** [comment]
Thanks for posting this! I managed to fix it by myself once you mentioned HookModule.
