### ISSUE TITLE
Force to play with my other controller

### ISSUE THREAD

**Issue by SAM1430B** [samuelgr/Xidi#87]
Thank you for the saviour project it's very useful for the old games.

I wonder if i can force Xidi to use my 3rd or 4th Xinput controller as the 1st controller in the game?

I've looked into the configuration document and haven't found anything related to that.

**Comment by samuelgr** [comment]
I wonder if [`ActiveVirtualControllerMask`](https://github.com/samuelgr/Xidi?tab=readme-ov-file#workarounds) would help with this?

**Comment by SAM1430B** [comment]
> I wonder if [`ActiveVirtualControllerMask`](https://github.com/samuelgr/Xidi?tab=readme-ov-file#workarounds) would help with this?

Nice, this worked. I had to set `ActiveVirtualControllerMask = 0x06` for the second controller and add `Type.2` under `[Mapper]` to use the `[CustomMapper]`
