### ISSUE TITLE
[Enhancement] Append the original device's name to the virtual device

### ISSUE THREAD

**Issue by BinToss** [samuelgr/Xidi#9]
When four virtualized devices all have the same device name, the only way to differ one from the other is by their inputs.
I propose changing the virtual devices names to a pattern such as "Xidi - [XInput Device Name]" e.g. "Xidi - Xbox One for Windows".

![haloce 2021-03-07 20-37-18](https://user-images.githubusercontent.com/7243190/110275028-1aaf3500-7f85-11eb-8e80-4779ede10b72.png)

**Comment by BinToss** [comment]
Although there aren't enough characters for it, a "Xidi - [custom/preset mapping name] - [XInput Device Name]" pattern could be helpful as well.

**Comment by BinToss** [comment]
After thinking about this again, I see how this wouldn't always work.
If Controller 1 is disconnected and another controller of a different make and model is connected to replace it, the virtual controller's device name would no longer be correct...

**Comment by samuelgr** [comment]
Right, and it is conceivable that a game could cache whatever controller names it sees on first enumeration. For example, unplugging an Xbox One controller and replacing it with an Xbox 360 controller could result in the game still saying "Xbox One Controller" when that is in fact wrong.

It used to be that controllers had lights on their faces to show what player number they are so it would be easy to tell. The newer controllers no longer feature these lights, and I am not sure what Microsoft had in mind as the right way of telling one player's controller from another. Modern Nintendo Switch controllers, for example, still have lights.

**Comment by BinToss** [comment]
Ah, I remember the controller lights. Ever since the Xbox 360 Controller
support on Windows started being shafted, QoL features like that and
battery monitors got left in the past.

**Comment by samuelgr** [comment]
Making this change would be functionally incorrect for the reasons earlier in this thread.
